global using Xunit;
global using Microsoft.Extensions.Logging;
global using Moq;
global using SimpleBankAPI.Application.Interfaces;
global using SimpleBankAPI.Application.Usecases;
global using SimpleBankAPI.Core.Entities;
global using SimpleBankAPI.Core.Enums;
global using SimpleBankAPI.Infrastructure.Ports.Repositories;
global using SimpleBankAPI.Application.Enums;